/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "phone_book.h"


void
phone_book_prog_1(char *host)
{
	CLIENT *clnt;
	r_val  *result_1;
	entry  add_to_database_1_arg;
	r_val  *result_2;
	char * remove_from_database_1_arg;
	r_val  *result_3;
	char * lookup_name_1_arg;
	r_val  *result_4;
	char *list_1_arg;
	int  *result_5;
	char *quit_1_arg;
	int  *result_6;
	char *terminate_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PHONE_BOOK_PROG, PHONE_BOOK_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_to_database_1(&add_to_database_1_arg, clnt);
	if (result_1 == (r_val *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = remove_from_database_1(&remove_from_database_1_arg, clnt);
	if (result_2 == (r_val *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = lookup_name_1(&lookup_name_1_arg, clnt);
	if (result_3 == (r_val *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = list_1((void*)&list_1_arg, clnt);
	if (result_4 == (r_val *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = quit_1((void*)&quit_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = terminate_1((void*)&terminate_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	phone_book_prog_1 (host);
exit (0);
}
